// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpdjcfuwyqlasffsbugt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwZGpjZnV3eXFsYXNmZnNidWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjMwNjUsImV4cCI6MjA2NjkzOTA2NX0.50m4jTuTZJ452jyWuAuN2vudqEK1n8UbvcdH6zxh1-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});